"""add document intelligence metadata

Revision ID: 0a9358754cd6
Revises: 
Create Date: 2026-07-10 19:57:08.186036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9358754cd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('processing_completed_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('extracted_character_count', sa.BigInteger(), nullable=True))
    op.add_column('documents', sa.Column('extracted_section_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('generated_chunk_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('embedding_provider', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('embedding_dimensions', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('chunking_strategy', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('vector_collection_name', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'vector_collection_name')
    op.drop_column('documents', 'chunking_strategy')
    op.drop_column('documents', 'embedding_dimensions')
    op.drop_column('documents', 'embedding_provider')
    op.drop_column('documents', 'embedding_model')
    op.drop_column('documents', 'generated_chunk_count')
    op.drop_column('documents', 'extracted_section_count')
    op.drop_column('documents', 'extracted_character_count')
    op.drop_column('documents', 'processing_completed_at')
    op.drop_column('documents', 'processing_started_at')
    # ### end Alembic commands ###
